### ISSUE TITLE
Difference between this image and an official one

### ISSUE THREAD

**Issue by jakubka** [webdizz/docker-sonarqube#1]
Hey @webdizz,

What is the difference (if any) between this image and an official one published by SonarQube: https://hub.docker.com/_/sonarqube/?

Is there any advantage of using your image?

Cheers

**Comment by webdizz** [comment]
Hi @jakubka,

There is not too much differences except it's based on `phusion/baseimage` and Oracle Java 8 and is assumed to be used with [webdizz/sonarqube-plugins](https://registry.hub.docker.com/u/webdizz/sonarqube-plugins/) image where set of plugins are pre-installed.
